### ISSUE TITLE
Approval and breeding order

### ISSUE THREAD

**Issue by KittiesInLove** [KittiesInLove/kittiesinlove.github.io#3]
@wooolfgang Thanks for the nice design! One thing: the order should be 1. Approval of Siring and 2. Check Breeding/ Breeding imo, because you always approve first and breed second. I got feedback that we need to explain it better. What do you think of bullet points, like 
1. Approval headline
2. Breeding headline

**Comment by stoesky** [comment]
Makes sense! I'll put the approval of siring at the top before breeding / check breeding. I'll also add tooltips explaining the procedure on how to breed properly. I can update this later.

**Comment by KittiesInLove** [comment]
Great!

**Comment by KittiesInLove** [comment]
It might be even better to use 2 tabs instead of a list because the tool is always used by two users/friends at the same time.
tab1: "My kitty wants to sire!"
Approval..
tab2: "My kitty wants to breed.."
Breeding/check breeding..


@wooolfgang what do you think?

**Comment by KittiesInLove** [comment]
not sure though, the list might be just as good. Please decide for the best UI @wooolfgang :)

**Comment by stoesky** [comment]
Okay. I can implement the tabs! I can work on it asap tomorrow though, I still have a project to finish today 🐐
